# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 branches:
  include: 
   - main

parameters:
- name: skipTests
  displayName: Skip Unit Tests?
  type: boolean
  default: false

pool:
  name: MyPool

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    options: ${{ parameters.skipTests == true && '-DskipTests' || '' }}
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: 'default'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    echo Starting the application
    java -cp target/my-app-1.0-SNAPSHOT.jar com.mycompany.app.App
  displayName: 'Run a multi-line script'

# 4. Upload the JAR to Azure (The new part!)
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'target/my-app-1.0-SNAPSHOT.jar'
    ArtifactName: 'MyJavaApp'
    publishLocation: 'Container'
  displayName: 'Upload JAR to Azure'
